# Generated by Django 5.2.7 on 2025-10-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='dias_vacaciones_extraordinarios',
            field=models.PositiveIntegerField(default=0, verbose_name='Días de Vacaciones Extraordinarios Usados'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultimo_reset_vacaciones',
            field=models.DateField(blank=True, null=True, verbose_name='Último Reset de Vacaciones'),
        ),
    ]
