# Generated by Django 4.2.7 on 2025-09-23 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='vacacion',
            name='aprobado_jefe',
            field=models.BooleanField(default=False, verbose_name='Aprobado por Jefe'),
        ),
        migrations.AddField(
            model_name='vacacion',
            name='aprobado_rh',
            field=models.BooleanField(default=False, verbose_name='Aprobado por RH'),
        ),
        migrations.AddField(
            model_name='vacacion',
            name='etapa',
            field=models.CharField(choices=[('EMP', 'Solicitada por Empleado'), ('JEF', 'Revisión de Jefe'), ('RH', 'Revisión de RH'), ('FIN', 'Finalizada')], default='EMP', max_length=3, verbose_name='Etapa'),
        ),
        migrations.AddField(
            model_name='vacacion',
            name='motivo_extraordinario',
            field=models.TextField(blank=True, verbose_name='Motivo Extraordinario'),
        ),
        migrations.AddField(
            model_name='vacacion',
            name='tipo',
            field=models.CharField(choices=[('N', 'Normal'), ('E', 'Extraordinaria')], default='N', max_length=1, verbose_name='Tipo'),
        ),
    ]
