# Generated by Django 5.2.7 on 2025-10-14 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_add_vacation_extra_fields'),
        ('empleados', '0003_configuracionsistema_remove_vacacion_empleado_and_more'),
    ]

    operations = [
    ]
