# Generated by Django 5.2.7 on 2025-10-21 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_add_dias_vacaciones_acumulados'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría de Equipo',
                'verbose_name_plural': 'Categorías de Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='dias_vacaciones_extraordinarios',
            field=models.PositiveIntegerField(default=0, verbose_name='Días de Vacaciones Extraordinarios Usados'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultimo_reset_vacaciones',
            field=models.DateField(blank=True, null=True, verbose_name='Último Reset de Vacaciones'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_perfil',
            field=models.CharField(choices=[('EMPLEADO', 'Empleado'), ('JEFE_AREA', 'Jefe de Área'), ('RH', 'Recursos Humanos'), ('SISTEMAS', 'Sistemas/IT'), ('ADMIN', 'Administrador')], max_length=20, verbose_name='Tipo de Perfil'),
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('codigo_inventario', models.CharField(max_length=50, unique=True, verbose_name='Código de Inventario')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADO', 'Asignado'), ('EN_REPARACION', 'En Reparación'), ('DADO_DE_BAJA', 'Dado de Baja')], default='DISPONIBLE', max_length=20, verbose_name='Estado')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de Adquisición')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.categoriaequipo', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['-fecha_adquisicion'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(verbose_name='Fecha de Asignación')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución')),
                ('condicion_entrega', models.CharField(blank=True, max_length=200, verbose_name='Condición al Entregar')),
                ('condicion_devolucion', models.CharField(blank=True, max_length=200, verbose_name='Condición al Devolver')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to='empleados.perfil', verbose_name='Asignado Por')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_asignados', to='empleados.perfil', verbose_name='Empleado')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='empleados.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Asignación de Equipo',
                'verbose_name_plural': 'Asignaciones de Equipos',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('RED', 'Red/Conectividad'), ('ACCESO', 'Acceso/Permisos'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='Área')),
                ('dispositivo', models.CharField(blank=True, max_length=100, verbose_name='Dispositivo Afectado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20, verbose_name='Prioridad')),
                ('descripcion', models.TextField(verbose_name='Descripción del Problema')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('RESUELTO', 'Resuelto'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('solucion', models.TextField(blank=True, verbose_name='Solución Aplicada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Asignación')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='empleados.perfil', verbose_name='Asignado A')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to='empleados.perfil', verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
